sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker build -t tdr/primordial -f Dockerfile.test .
  - docker run -it --rm --name primordial_test tdr/primordial
  - docker build -t tripdubroot/primordial .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tripdubroot/primordial;
    fi
