FROM node:alpine

COPY . /app
WORKDIR /app
RUN npm install

EXPOSE 6996

ENTRYPOINT ["npm", "test"]

# docker build -t tdr/primoridial -f ./Dockerfile.test
# docker run -d --name primordial_test tdr/primordial
